#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


pod 'Vokoder', '~> 1.0.13'
pod 'gtm-oauth2', '~> 1.0.125'
pod 'SSKeychain', '~> 1.2.2'

#swift pods for cocoapods 0.36
pod 'SwiftyJSON', :git => "git@github.com:SwiftyJSON/SwiftyJSON.git", :branch => 'xcode6.3'
pod 'Alamofire', :git => "git@github.com:Alamofire/Alamofire.git", :branch => 'xcode-6.3'

target :SoundieTests, :exclusive => true do
    pod 'VOKMockUrlProtocol', '~> 2.0'
end